###
get http://localhost:3001/

###
post http://localhost:3001/api/blogs
Content-Type: application/json 

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "https://homepages.cwi.nl/~storm/teaching/reader/Dijkstra68.pdf",
    "likes": 5
}

### 
post http://localhost:3001/api/users
Content-Type: application/json 

{
    "username": "hellas",
    "name": "Arto Hellas"
}