###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test 2",
    "author": "Test Author",
    "url": "test2.com",
    "likes": 1
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "password": "password"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "test",
    "password": "password"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

### 
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY4YzI5MjljODdjYTY5Y2I5NDdlOTczZiIsImlhdCI6MTc1NzY1NzQ0N30.g3-XGhIMhxRWRGC2D7yXdd0F_iURE5-X0FgWGsqIVfo

{
    "title": "authorized blog title 2",
    "url": "authblog.com",
    "author": "authorizated author",
    "likes": 0
}

### 
DELETE http://localhost:3003/api/blogs/68baea3517f249c1f8bf6f97
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY4YmFkYzg1MTBkYzQyOWRhMjRjM2JmMiIsImlhdCI6MTc1NzA3NzU2NH0.Ub1FMlicII9ebAf_sQmAMOuHG2vkV1NDiHq5lRaSrG0

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "testuser",
    "name": "Test User",
    "password": "testpassword"
}