###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY4Yjk4Y2NkNDdlYTQ5MjhmNTJjNDgzZiIsImlhdCI6MTc1Njk5MjM2OX0.nBsCqnIhh_ILHWgVqcyA63xxRmL_zd6u-X4KkmEsdhs

{
    "title": "new blog",
    "author": "Test Author",
    "url": "test2.com",
    "likes": 1
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}